keys:
  - &jason age1z8cyzwua7d7vmvgvxznfsq9rhr9wu8pu82vk0tznl6z8w8hsr90sm3dnsg
  - &server age1gp3n4zcwuycm9nk3ey5pvqymsdrg4wlzu3vk2p7twvxvpmdyvahqdglzcj
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
        - *jason
        - *server
