# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [(modulesPath + "/installer/scan/not-detected.nix")];

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "kvm-amd" "nvidia.NVreg_EnableGpuFirmware=0"]; # Fix for nvidia stuttering in KDE. Should be fixed in future driver update. (24-07-16)
    extraModulePackages = [ ];
  };

  fileSystems = {

    "/mnt/Games_HDD" = {
      device = "/dev/disk/by-uuid/8575ae67-7e62-4f00-bb00-63022d128831";
      fsType = "ext4";
    };
    
    "/mnt/Games_SSD" = { 
      device = "/dev/disk/by-uuid/9cf976f6-754f-474b-bc49-56dd5705b640";
      fsType = "ext4";
    };
    
    "/mnt/Main_storage" = {
      device = "/dev/disk/by-uuid/c765f3f4-c218-4baa-ab51-20edd0b67454";
      fsType = "ext4";
    };
    
    "/" = {
      device = "/dev/disk/by-uuid/8a694e3d-00d9-4673-bff7-072c6d438e5b";
      fsType = "ext4";
    };

    "/boot" = {
      device = "/dev/disk/by-uuid/C9FA-ADF8";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp5s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
