# Enable Project Zomboid server

{ pkgs, lib, config, ... }:

{
  # SOPS Secret Setup
  sops.secrets.project-zomboid_admin_pwd.owner = "zomboid";

  # System User & Group Setup
  users.users.zomboid = {
    isSystemUser = true;
    group = "zomboid";
    uid = 99; # Matches the UID expected by the container environment
  };
  users.groups.zomboid.gid = 100; # Matches the GID (often 'users' or 100)

  # Host Directory Provisioning
  systemd.tmpfiles.rules = [
    "d /var/lib/projectzomboid 0770 zomboid zomboid -"
    "d /var/lib/steamcmd 0770 zomboid zomboid -"
  ];

  # Host Firewall Configuration
  networking.firewall.allowedUDPPorts = [ 
    16261 # Main handshake port
    16262 # Direct connection UDP
  ];
  networking.firewall.allowedTCPPorts = [ 
    29015 # Steam query port
    16262 # Direct connection TCP
  ] ++ (lib.range 16263 16282); # Dynamically opens player slots 1 through 20 (16263 to 16282)

  # Docker Runtime Configuration
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Project Zomboid Container Configuration
  virtualisation.oci-containers.containers."project-zomboid" = {
    image = "ich777/steamcmd:projectzomboid";
    environment = {
      "GAME_ID" = "380870 -beta 42.13.1";
      "GID" = "100";
      "HOST_CONTAINERNAME" = "project-zomboid";
      "HOST_HOSTNAME" = "knight";
      "HOST_OS" = "NixOS";
      "TZ" = "America/Toronto";
      "UID" = "99";
      "VALIDATE" = "true";
    };
    volumes = [
      "/var/lib/projectzomboid:/serverdata/serverfiles:rw"
      "/var/lib/steamcmd:/serverdata/steamcmd:rw"
    ];
    ports = [
      "29015:27015/tcp"  # Steam query port
      "16261:16261/udp"  # Main handshake port
      "16262:16262/udp"  # Direct connection
      "16262:16262/tcp"
      
      # Player slots 1 through 20
      "16263:16263/tcp"
      "16264:16264/tcp"
      "16265:16265/tcp"
      "16266:16266/tcp"
      "16267:16267/tcp"
      "16268:16268/tcp"
      "16269:16269/tcp"
      "16270:16270/tcp"
      "16271:16271/tcp"
      "16272:16272/tcp"
      "16273:16273/tcp"
      "16274:16274/tcp"
      "16275:16275/tcp"
      "16276:16276/tcp"
      "16277:16277/tcp"
      "16278:16278/tcp"
      "16279:16279/tcp"
      "16280:16280/tcp"
      "16281:16281/tcp"
      "16282:16282/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=steamcmd"
      "--network=project-zomboid_default"
    ];
  };

  # Systemd Infrastructure Mapping
  systemd.services."docker-project-zomboid" = {
    serviceConfig = {
      EnvironmentFile = config.sops.secrets.project-zomboid_admin_pwd.path;
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [ "docker-network-project-zomboid_default.service" ];
    requires = [ "docker-network-project-zomboid_default.service" ];
    partOf = [ "docker-compose-project-zomboid-root.target" ];
    wantedBy = [ "docker-compose-project-zomboid-root.target" ];
  };

  systemd.services."docker-network-project-zomboid_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f project-zomboid_default";
    };
    script = ''
      docker network inspect project-zomboid_default || docker network create project-zomboid_default
    '';
    partOf = [ "docker-compose-project-zomboid-root.target" ];
    wantedBy = [ "docker-compose-project-zomboid-root.target" ];
  };

  systemd.targets."docker-compose-project-zomboid-root" = {
    unitConfig.Description = "Root target generated by compose2nix.";
    wantedBy = [ "multi-user.target" ];
  };
}