# Enable Project Zomboid server

{ pkgs, lib, config, ... }:

{
  # SOPS Secret Setup
  sops.secrets.project-zomboid_admin_pwd.owner = "zomboid";

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # System User & Group Setup
  users.users.zomboid = {
    isSystemUser = true;
    group = "zomboid";
    # SubUID/SubGID allocations allow Podman to safely map container internal permissions
    subUidRanges = [{ startUid = 100000; count = 65536; }];
    subGidRanges = [{ startGid = 100000; count = 65536; }];
  };
  users.groups.zomboid = {};

  # Host Directory Provisioning
  systemd.tmpfiles.rules = [
    "d /var/lib/projectzomboid 0775 zomboid zomboid -"
    "d /var/lib/steamcmd 0775 zomboid zomboid -"
  ];

  # Host Firewall Configuration
  networking.firewall.allowedUDPPorts = [ 
    16261 # Main handshake port
    16262 # Direct connection UDP
  ];
  networking.firewall.allowedTCPPorts = [ 
    29015 # Steam query port
    16262 # Direct connection TCP
  ] ++ (lib.range 16263 16282); # Dynamically opens player slots 1 through 20 (16263 to 16282)

  # Containers
  virtualisation.oci-containers.containers."project-zomboid" = {
    image = "ich777/steamcmd:projectzomboid";
    environment = {
      "GAME_ID" = "380870 -beta b42test"; 
      "HOST_CONTAINERNAME" = "project-zomboid";
      "HOST_HOSTNAME" = "knight";
      "HOST_OS" = "NixOS";
      "TZ" = "America/Toronto";
      "VALIDATE" = "true";
    };
    volumes = [
      "/var/lib/projectzomboid:/serverdata/serverfiles:rw"
      "/var/lib/steamcmd:/serverdata/steamcmd:rw"
    ];
    ports = [
      "29015:27015/tcp"  # Steam query port
      "16261:16261/udp"  # Main handshake port
      "16262:16262/udp"  # Direct connection
      "16262:16262/tcp"
      
      # Player slots 1 through 20
      "16263:16263/tcp" "16264:16264/tcp" "16265:16265/tcp" "16266:16266/tcp"
      "16267:16267/tcp" "16268:16268/tcp" "16269:16269/tcp" "16270:16270/tcp"
      "16271:16271/tcp" "16272:16272/tcp" "16273:16273/tcp" "16274:16274/tcp"
      "16275:16275/tcp" "16276:16276/tcp" "16277:16277/tcp" "16278:16278/tcp"
      "16279:16279/tcp" "16280:16280/tcp" "16281:16281/tcp" "16282:16282/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=steamcmd"
      "--network=project-zomboid_default"
    ];
  };
  systemd.services."podman-project-zomboid" = {
    serviceConfig = {
      EnvironmentFile = config.sops.secrets.project-zomboid_admin_pwd.path;
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [ "podman-network-project-zomboid_default.service" ];
    requires = [ "podman-network-project-zomboid_default.service" ];
    partOf = [ "podman-compose-project-zomboid-root.target" ];
    wantedBy = [ "podman-compose-project-zomboid-root.target" ];
  };

  # Networks
  systemd.services."podman-network-project-zomboid_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.podman}/bin/podman network rm -f project-zomboid_default";
    };
    script = ''
      podman network inspect project-zomboid_default || podman network create project-zomboid_default
    '';
    partOf = [ "podman-compose-project-zomboid-root.target" ];
    wantedBy = [ "podman-compose-project-zomboid-root.target" ];
  };

  # Root service
  systemd.targets."podman-compose-project-zomboid-root" = {
    unitConfig.Description = "Root target generated by compose2nix.";
    wantedBy = [ "multi-user.target" ];
  };
}