# Enable Wallabag server

{ pkgs, lib, config, ... }:

{
  # SOPS Secret Setup
  sops.secrets.wallabag_env.owner = "wallabag";

  # Runtime
  virtualisation.podman = {
    enable = true;
    autoPrune.enable = true;
    dockerCompat = true;
  };

  # Enable container name DNS for all Podman networks.
  networking.firewall.interfaces = let
    matchAll = if !config.networking.nftables.enable then "podman+" else "podman*";
  in {
    "${matchAll}".allowedUDPPorts = [ 53 ];
  };

  virtualisation.oci-containers.backend = "podman";

  # System User & Group Setup
  users.users.wallabag = {
    isSystemUser = true;
    group = "wallabag";
    # SubUID/SubGID allocations allow Podman to safely map container internal permissions
    subUidRanges = [{ startUid = 200000; count = 65536; }];
    subGidRanges = [{ startGid = 200000; count = 65536; }];
  };
  users.groups.wallabag = {};

  # Host Directory Provisioning
  systemd.tmpfiles.rules = [
    "d /var/lib/wallabag/data 0775 wallabag wallabag -"
    "d /var/lib/wallabag/images 0775 wallabag wallabag -"
    "d /var/lib/wallabag/app-data 0775 wallabag wallabag -"
  ];

  # Host Firewall Configuration
  networking.firewall.allowedTCPPorts = [ 80 ];

  # Containers
  virtualisation.oci-containers.containers."wallabag-db" = {
    image = "mariadb";
    volumes = [
      "/var/lib/wallabag/data:/var/lib/mysql:rw"
    ];
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"/usr/local/bin/healthcheck.sh\", \"--innodb_initialized\"]"
      "--health-interval=20s"
      "--health-timeout=3s"
      "--network-alias=db"
      "--network=wallabag_default"
    ];
  };
  systemd.services."podman-wallabag-db" = {
    serviceConfig = {
      EnvironmentFile = config.sops.secrets.wallabag_env.path;
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wallabag_default.service"
    ];
    requires = [
      "podman-network-wallabag_default.service"
    ];
    partOf = [
      "podman-compose-wallabag-root.target"
    ];
    wantedBy = [
      "podman-compose-wallabag-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wallabag-redis" = {
    image = "redis:alpine";
    log-driver = "journald";
    extraOptions = [
      "--health-cmd=[\"redis-cli\", \"ping\"]"
      "--health-interval=20s"
      "--health-timeout=3s"
      "--network-alias=redis"
      "--network=wallabag_default"
    ];
  };
  systemd.services."podman-wallabag-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
    };
    after = [
      "podman-network-wallabag_default.service"
    ];
    requires = [
      "podman-network-wallabag_default.service"
    ];
    partOf = [
      "podman-compose-wallabag-root.target"
    ];
    wantedBy = [
      "podman-compose-wallabag-root.target"
    ];
  };
  virtualisation.oci-containers.containers."wallabag-wallabag" = {
    image = "wallabag/wallabag";
    environment = {
      "SYMFONY__ENV__DATABASE_CHARSET" = "utf8mb4";
      "SYMFONY__ENV__DATABASE_DRIVER" = "pdo_mysql";
      "SYMFONY__ENV__DATABASE_HOST" = "db";
      "SYMFONY__ENV__DATABASE_NAME" = "wallabag";
      "SYMFONY__ENV__DATABASE_PORT" = "3306";
      "SYMFONY__ENV__DATABASE_TABLE_PREFIX" = "wallabag_";
      "SYMFONY__ENV__DATABASE_USER" = "wallabag";
    };
    volumes = [
      "/var/lib/wallabag/images:/var/www/wallabag/web/assets/images:rw"
      "/var/lib/wallabag/app-data:/var/www/wallabag/data:rw"
    ];
    ports = [
      "80:80/tcp"
    ];
    dependsOn = [
      "wallabag-db"
      "wallabag-redis"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=wallabag"
      "--network=wallabag_default"
    ];
  };
  systemd.services."podman-wallabag-wallabag" = {
    serviceConfig = {
      EnvironmentFile = config.sops.secrets.wallabag_env.path;
      Restart = lib.mkOverride 90 "always";
    };
    after = [ "podman-network-wallabag_default.service" ];
    requires = [ "podman-network-wallabag_default.service" ];
    partOf = [ "podman-compose-wallabag-root.target" ];
    wantedBy = [ "podman-compose-wallabag-root.target" ];
  };

  # Networks
  systemd.services."podman-network-wallabag_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f wallabag_default";
    };
    script = ''
      podman network inspect wallabag_default || podman network create wallabag_default
    '';
    partOf = [ "podman-compose-wallabag-root.target" ];
    wantedBy = [ "podman-compose-wallabag-root.target" ];
  };

  # Root service
  systemd.targets."podman-compose-wallabag-root" = {
    unitConfig.Description = "Root target generated by compose2nix.";
    wantedBy = [ "multi-user.target" ];
  };
}
